github_token = "ghp_"

[graph_colors]
level1 = "13,68,41"
level2 = "0,255,0"
level3 = "0,0,255"
level4 = "255,0,0"

[text_colors]
info_color = "0,255,255"

[graph_data]
percentiles = [
    0,
    30,
    60,
    90,
]
