- name: IRIS
  status: active
  added: "2026-07-31"
  github: github.com/versenilvis/IRIS
- name: portview
  status: active
  added: "2026-07-31"
  github: github.com/Mapika/portview
- name: keepkit
  status: active
  added: "2026-07-31"
  github: github.com/stanlyzoolo/keepkit
- name: patent
  status: active
  added: "2026-08-05"
  github: github.com/r14dd/patent
- name: netwatch
  status: active
  added: "2026-08-05"
  github: github.com/matthart1983/netwatch
- name: tuistore
  status: active
  added: "2026-08-06"
  github: github.com/Gheat1/tuistore
- name: river
  status: active
  added: "2026-08-11"
  github: github.com/freenet/river
- name: late-sh
  status: active
  added: "2026-08-12"
  github: github.com/mpiorowski/late-sh
- name: Ligaturizer
  status: active
  added: "2026-08-12"
  github: github.com/ToxicFrog/Ligaturizer
- name: hyprls
  status: active
  added: "2026-08-12"
  github: github.com/hyprland-community/hyprls
- name: Kiro
  status: active
  added: "2026-08-12"
  github: github.com/kirodotdev/Kiro
- name: TakaTime
  status: active
  added: "2026-08-12"
  github: github.com/Rtarun3606k/TakaTime
- name: desktop-wakatime
  status: active
  added: "2026-08-12"
  github: github.com/wakatime/desktop-wakatime
- name: terminal-browser
  status: active
  added: "2026-08-14"
  github: github.com/zenbu-labs/terminal-browser
- name: golazo
  status: active
  added: "2026-08-16"
  github: github.com/0xjuanma/golazo
- name: lsoff
  status: active
  added: "2026-08-20"
  github: github.com/yutat23/lsoff
- name: valveFM
  status: active
  added: "2026-08-22"
  github: github.com/Zorig/valveFM
- name: syswatch
  status: active
  added: "2026-08-24"
  github: github.com/matthart1983/syswatch
- name: diskwatch
  status: active
  added: "2026-08-24"
  github: github.com/matthart1983/diskwatch
