- name: IRIS
  status: active
  added: "2026-07-31"
  github: github.com/versenilvis/IRIS
- name: portview
  status: active
  added: "2026-07-31"
  github: github.com/Mapika/portview
- name: keepkit
  status: active
  added: "2026-07-31"
  github: github.com/stanlyzoolo/keepkit
- name: patent
  status: active
  added: "2026-08-05"
  github: github.com/r14dd/patent
- name: netwatch
  status: active
  added: "2026-08-05"
  github: github.com/matthart1983/netwatch
- name: tuistore
  status: active
  added: "2026-08-06"
  github: github.com/Gheat1/tuistore
