border = "#292e42"
accent = "#7dcfff"
muted = "#565f89"
text = "#c0caf5"
text_sel = "#ffffff"
key = "#bb9af7"
match = "#73daca"
desc = "#9aa5ce"
desc_sel = "#c0caf5"
sel_bg = "#292e42"
sel_text = "#000000"
scroll_info = "#7aa2f7"
ghost_text = "#565f89"
sys = "#292e42"
sys_sel = "#f7768e"
hist = "#1f2335"
hist_sel = "#7dcfff"
alias = "#292e42"
alias_sel = "#bb9af7"
