# Monitor Configuration
# See Hyprland wiki for more details
# https://wiki.hyprland.org/Configuring/Monitors/

# Monitors
monitorv2 {
  output = HDMI-A-3
  mode = 3840x2160@60.0
  position = 0x0
  scale = 1.5
  bitdepth = 10
  cm = hdr
  sdrbrightness = 1.5
  sdrsaturation = 1.o
}

# QEMU-KVM, virtual box or vmware
monitorv2 {
  output = Virtual-1
  mode = 1920x1080@60
  position = auto
  scale = 1.0
  bitdepth = auto
  cm = auto
}

