export FZF_DEFAULT_OPTS=" \
  --style=full \
  --highlight-line \
  --info=inline-right \
  --ansi \
  --layout=reverse \
  --border=rounded \
  --color=bg+:#1a1b26 \
  --color=border:#1a1b26 \
  --color=fg:#c0caf5 \
  --color=gutter:#16161e \
  --color=header:#ff9e64 \
  --color=hl+:#2ac3de \
  --color=hl:#2ac3de \
  --color=info:#545c7e \
  --color=marker:#ff007c \
  --color=pointer:#ff007c \
  --color=prompt:#2ac3de \
  --color=query:#c0caf5:regular \
  --color=scrollbar:#1a1b26 \
  --color=separator:#ff9e64 \
  --color=spinner:#ff007c \
"
