github_token = "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"

[graph_colors]
level1 = "0,255,0"
level2 = "160,32,240"
level3 = "0,0,255"
level4 = "255,0,0"

[text_colors]
info_color = "0,255,255"

[graph_data]
percentiles = [
    0,
    30,
    60,
    90,
]
